### ISSUE TITLE
Support building certs from hosts ansible groups, rather than hostvar! 

### ISSUE THREAD

**Issue by NickHerrig** [NickHerrig/ansible-role-nebula#9]
Experiment and see whether the usage is cleaner. 
Rather than defining a string "webserver,ubuntu,digitalocean" in hostsvars:
```yaml
    nebula:
      hosts:
        lighthouse.nebula.nickherrig.com:
          nebula_is_lighthouse: true
          nebula_hostname: lighthouse
          nebula_ip: 10.100.14.1
          nebula_groups: "webserver,ubuntu,digitalocean"
```

I'm wondering if building the list from ansible groups would be a cleaner implementation. 
something like...

```yaml
[webserver]
host

[ubuntu]
host

[digitalocean]
host
```

The role logic would be a little more complex, possible a good uscase for filter plugins.. 
But one less var to defined per group, and then go back and change, when you add groups eventually..
